"""initial schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    # Employers table
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employers_id'), 'employers', ['id'], unique=False)
    
    # JobSeekerProfiles table
    op.create_table('job_seeker_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('current_role', sa.String(length=100), nullable=True),
    sa.Column('current_company', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_index(op.f('ix_job_seeker_profiles_id'), 'job_seeker_profiles', ['id'], unique=False)
    
    # Jobs table
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('experience_required', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], )
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index('ix_jobs_is_active', 'jobs', ['is_active'], unique=False)
    
    # Applications table with enum
    application_state = postgresql.ENUM(
        'APPLIED', 'SHORTLISTED', 'INTERVIEW', 'OFFERED', 'HIRED', 
        'REJECTED', 'WITHDRAWN', 'CLOSED',
        name='applicationstate'
    )
    application_state.create(op.get_bind())
    
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('state', application_state, nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_state_change', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['job_seeker_profiles.id'], ),
    sa.UniqueConstraint('job_id', 'profile_id', name='uq_job_profile')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index('ix_applications_state', 'applications', ['state'], unique=False)
    
    # InterviewSessions table with enum
    interview_session_state = postgresql.ENUM(
        'STARTED', 'ABORTED', 'COMPLETED',
        name='interviewsessionstate'
    )
    interview_session_state.create(op.get_bind())
    
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('state', interview_session_state, nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], )
    )
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.create_index('ix_interview_sessions_state', 'interview_sessions', ['state'], unique=False)
    op.create_index('ix_interview_sessions_application_id', 'interview_sessions', ['application_id'], unique=False)
    
    # MatchRuns table with enum
    match_run_status = postgresql.ENUM(
        'PENDING', 'RUNNING', 'COMPLETED', 'CANCELLED', 'FAILED',
        name='matchrunstatus'
    )
    match_run_status.create(op.get_bind())
    
    op.create_table('match_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('status', match_run_status, nullable=False),
    sa.Column('input_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('total_jobs_considered', sa.Integer(), nullable=True),
    sa.Column('total_matches_found', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['profile_id'], ['job_seeker_profiles.id'], )
    )
    op.create_index(op.f('ix_match_runs_id'), 'match_runs', ['id'], unique=False)
    op.create_index('ix_match_runs_status', 'match_runs', ['status'], unique=False)
    op.create_index('ix_match_runs_profile_id', 'match_runs', ['profile_id'], unique=False)
    op.create_index('ix_match_runs_profile_version', 'match_runs', ['profile_version'], unique=False)
    
    # MatchLogs table
    op.create_table('match_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_run_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reasons', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('considered_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['match_run_id'], ['match_runs.id'], ),
    sa.UniqueConstraint('match_run_id', 'job_id', name='uq_match_run_job')
    )
    op.create_index(op.f('ix_match_logs_id'), 'match_logs', ['id'], unique=False)
    op.create_index('ix_match_logs_match_run_id', 'match_logs', ['match_run_id'], unique=False)
    op.create_index('ix_match_logs_job_id', 'match_logs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_logs_job_id', table_name='match_logs')
    op.drop_index('ix_match_logs_match_run_id', table_name='match_logs')
    op.drop_index(op.f('ix_match_logs_id'), table_name='match_logs')
    op.drop_table('match_logs')
    
    op.drop_index('ix_match_runs_profile_version', table_name='match_runs')
    op.drop_index('ix_match_runs_profile_id', table_name='match_runs')
    op.drop_index('ix_match_runs_status', table_name='match_runs')
    op.drop_index(op.f('ix_match_runs_id'), table_name='match_runs')
    op.drop_table('match_runs')
    
    op.drop_index('ix_interview_sessions_application_id', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_state', table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    
    op.drop_index('ix_applications_state', table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    
    op.drop_index('ix_jobs_is_active', table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    
    op.drop_index(op.f('ix_job_seeker_profiles_id'), table_name='job_seeker_profiles')
    op.drop_table('job_seeker_profiles')
    
    op.drop_index(op.f('ix_employers_id'), table_name='employers')
    op.drop_table('employers')
    
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    # Drop enums
    match_run_status = postgresql.ENUM(name='matchrunstatus')
    match_run_status.drop(op.get_bind())
    
    interview_session_state = postgresql.ENUM(name='interviewsessionstate')
    interview_session_state.drop(op.get_bind())
    
    application_state = postgresql.ENUM(name='applicationstate')
    application_state.drop(op.get_bind())
    # ### end Alembic commands ###
